name: Build and Push to ACR
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: 'Build and Push to ACR'
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: 'your_database_url'

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AZURE_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push to ACR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.AZURE_URL }}/incstats:${{ github.sha }}
          file: Dockerfile
          build-args: |
            DATABASE_URL=your_database_url
      
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Redeploy Azure Container App
        run: |
          az containerapp revision copy \
            --name sbu-inslack-nea-app \
            --resource-group sbu-public-incstats-net-nea-rg \
            --cpu 0.5 \
            --memory 1.0 \
            --image ${{ secrets.AZURE_URL }}/incstats:${{ github.sha }}

            #TODO Make this app push a new revision to the azure container app. Currently you have to publish it manually
